name: Update Sitemap Lastmod

on:
  push:
    branches:
      - main

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    # スクリプトによる自動コミットが再度ワークフローをトリガーしないようにする
    if: "!contains(github.event.head_commit.message, 'chore(sitemap):')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # git pushするために必要
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run update script
        id: run_script
        run: |
          node <<'EOF'
          const fs = require('fs');
          const { execSync } = require('child_process');

          const sitemapPath = 'sitemap.xml';
          const today = new Date().toISOString().split('T')[0];
          let sitemap = fs.readFileSync(sitemapPath, 'utf8');

          // 今回のコミットで変更されたファイルに基づいてlastmodを更新
          const files = execSync('git diff-tree --no-commit-id --name-only -r HEAD').toString().split('\n');
          const locRegex = /<loc>https?:\/\/honeymarron\.com([^<]*)<\/loc>\s*<lastmod>([^<]*)<\/lastmod>/g;

          sitemap = sitemap.replace(locRegex, (match, path, oldDate) => {
            // path: URLパス (例: /, /en/, /apps/awardcert/)
            // file: 変更されたファイルパス (例: index.html, en/index.html, apps/awardcert.html)
            const fileMatchesPath = (file) => {
              const filePathAsUrl = '/' + file.replace(/index\.html$/, '');
              return filePathAsUrl === path || filePathAsUrl === path + '/';
            };

            if (files.some(fileMatchesPath)) {
              console.log(`Updating lastmod for ${path} to ${today}`);
              return match.replace(oldDate, today);
            }
            return match;
          });

          fs.writeFileSync(sitemapPath, sitemap);
          EOF

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # sitemap.xml に変更があったか確認
          if ! git diff --quiet sitemap.xml; then
            git add sitemap.xml
            git commit -m "chore(sitemap): update lastmod dates"
            git push
            echo "Sitemap updated and pushed."
          else
            echo "No changes to sitemap.xml."
          fi